"""empty message

Revision ID: 4b11e8c58ddc
Revises: 1752e20623bf
Create Date: 2024-03-14 13:40:59.628493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b11e8c58ddc'
down_revision = '1752e20623bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('num_rooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_brooms', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('num_brooms')
        batch_op.drop_column('num_rooms')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
