"""empty message

Revision ID: cdd5c2e9ae7d
Revises: 4b11e8c58ddc
Create Date: 2024-03-14 13:42:37.731534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd5c2e9ae7d'
down_revision = '4b11e8c58ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ptype', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pname', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('pname')
        batch_op.drop_column('location')
        batch_op.drop_column('ptype')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
