"""empty message

Revision ID: e5abb1c26100
Revises: faf7fb79021f
Create Date: 2024-03-19 23:26:34.477827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5abb1c26100'
down_revision = 'faf7fb79021f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('num_rooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('num_brooms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ptype', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pname', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pname')
        batch_op.drop_column('location')
        batch_op.drop_column('ptype')
        batch_op.drop_column('price')
        batch_op.drop_column('num_brooms')
        batch_op.drop_column('num_rooms')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
